# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from . import utilities, tables

class GetFloatingIpResult:
    """
    A collection of values returned by getFloatingIp.
    """
    def __init__(__self__, description=None, home_location=None, id=None, ip_address=None, ip_network=None, labels=None, selector=None, server_id=None, type=None, with_selector=None):
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        __self__.description = description
        if home_location and not isinstance(home_location, str):
            raise TypeError("Expected argument 'home_location' to be a str")
        __self__.home_location = home_location
        if id and not isinstance(id, float):
            raise TypeError("Expected argument 'id' to be a float")
        __self__.id = id
        if ip_address and not isinstance(ip_address, str):
            raise TypeError("Expected argument 'ip_address' to be a str")
        __self__.ip_address = ip_address
        if ip_network and not isinstance(ip_network, str):
            raise TypeError("Expected argument 'ip_network' to be a str")
        __self__.ip_network = ip_network
        if labels and not isinstance(labels, dict):
            raise TypeError("Expected argument 'labels' to be a dict")
        __self__.labels = labels
        if selector and not isinstance(selector, str):
            raise TypeError("Expected argument 'selector' to be a str")
        __self__.selector = selector
        if server_id and not isinstance(server_id, float):
            raise TypeError("Expected argument 'server_id' to be a float")
        __self__.server_id = server_id
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        __self__.type = type
        if with_selector and not isinstance(with_selector, str):
            raise TypeError("Expected argument 'with_selector' to be a str")
        __self__.with_selector = with_selector

async def get_floating_ip(id=None,ip_address=None,selector=None,with_selector=None,opts=None):
    """
    Provides details about a Hetzner Cloud Floating IP.
    
    This resource can be useful when you need to determine a Floating IP ID based on the IP address.
    
    ## Example Usage
    
    # Data Source: hcloud_floating_ip
    Provides details about a Hetzner Cloud Floating IP.
    This resource can be useful when you need to determine a Floating IP ID based on the IP address.
    """
    __args__ = dict()

    __args__['id'] = id
    __args__['ipAddress'] = ip_address
    __args__['selector'] = selector
    __args__['withSelector'] = with_selector
    __ret__ = await pulumi.runtime.invoke('hcloud:index/getFloatingIp:getFloatingIp', __args__, opts=opts)

    return GetFloatingIpResult(
        description=__ret__.get('description'),
        home_location=__ret__.get('homeLocation'),
        id=__ret__.get('id'),
        ip_address=__ret__.get('ipAddress'),
        ip_network=__ret__.get('ipNetwork'),
        labels=__ret__.get('labels'),
        selector=__ret__.get('selector'),
        server_id=__ret__.get('serverId'),
        type=__ret__.get('type'),
        with_selector=__ret__.get('withSelector'))
