// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package hcloud

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides details about a specific Hetzner Cloud Datacenter.
// Use this resource to get detailed information about specific datacenter.
func LookupDatacenter(ctx *pulumi.Context, args *GetDatacenterArgs) (*GetDatacenterResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["id"] = args.Id
		inputs["name"] = args.Name
	}
	outputs, err := ctx.Invoke("hcloud:index/getDatacenter:getDatacenter", inputs)
	if err != nil {
		return nil, err
	}
	return &GetDatacenterResult{
		AvailableServerTypeIds: outputs["availableServerTypeIds"],
		Description: outputs["description"],
		Id: outputs["id"],
		Location: outputs["location"],
		Name: outputs["name"],
		SupportedServerTypeIds: outputs["supportedServerTypeIds"],
	}, nil
}

// A collection of arguments for invoking getDatacenter.
type GetDatacenterArgs struct {
	Id interface{}
	Name interface{}
}

// A collection of values returned by getDatacenter.
type GetDatacenterResult struct {
	AvailableServerTypeIds interface{}
	Description interface{}
	Id interface{}
	Location interface{}
	Name interface{}
	SupportedServerTypeIds interface{}
}
