// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package hcloud

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides details about a Hetzner Cloud Image.
// This resource is useful if you want to use a non-terraform managed image.
func LookupImage(ctx *pulumi.Context, args *GetImageArgs) (*GetImageResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["id"] = args.Id
		inputs["mostRecent"] = args.MostRecent
		inputs["name"] = args.Name
		inputs["selector"] = args.Selector
		inputs["withSelector"] = args.WithSelector
		inputs["withStatuses"] = args.WithStatuses
	}
	outputs, err := ctx.Invoke("hcloud:index/getImage:getImage", inputs)
	if err != nil {
		return nil, err
	}
	return &GetImageResult{
		Created: outputs["created"],
		Deprecated: outputs["deprecated"],
		Description: outputs["description"],
		Id: outputs["id"],
		Labels: outputs["labels"],
		MostRecent: outputs["mostRecent"],
		Name: outputs["name"],
		OsFlavor: outputs["osFlavor"],
		OsVersion: outputs["osVersion"],
		RapidDeploy: outputs["rapidDeploy"],
		Selector: outputs["selector"],
		Type: outputs["type"],
		WithSelector: outputs["withSelector"],
		WithStatuses: outputs["withStatuses"],
	}, nil
}

// A collection of arguments for invoking getImage.
type GetImageArgs struct {
	Id interface{}
	MostRecent interface{}
	Name interface{}
	Selector interface{}
	WithSelector interface{}
	WithStatuses interface{}
}

// A collection of values returned by getImage.
type GetImageResult struct {
	Created interface{}
	Deprecated interface{}
	Description interface{}
	Id interface{}
	Labels interface{}
	MostRecent interface{}
	Name interface{}
	OsFlavor interface{}
	OsVersion interface{}
	RapidDeploy interface{}
	Selector interface{}
	Type interface{}
	WithSelector interface{}
	WithStatuses interface{}
}
