// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package hcloud

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides a list of available Hetzner Cloud Locations.
// This resource may be useful to create highly available infrastructure, distributed across several locations.
func LookupLocations(ctx *pulumi.Context, args *GetLocationsArgs) (*GetLocationsResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["locationIds"] = args.LocationIds
	}
	outputs, err := ctx.Invoke("hcloud:index/getLocations:getLocations", inputs)
	if err != nil {
		return nil, err
	}
	return &GetLocationsResult{
		Descriptions: outputs["descriptions"],
		LocationIds: outputs["locationIds"],
		Names: outputs["names"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getLocations.
type GetLocationsArgs struct {
	LocationIds interface{}
}

// A collection of values returned by getLocations.
type GetLocationsResult struct {
	Descriptions interface{}
	LocationIds interface{}
	Names interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
