# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from .. import utilities, tables

__config__ = pulumi.Config('hcloud')

endpoint = __config__.get('endpoint')

token = __config__.require('token')
"""
The API token to access the Hetzner cloud.
"""

