// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class FloatingIpAssignment extends pulumi.CustomResource {
    /**
     * Get an existing FloatingIpAssignment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FloatingIpAssignmentState, opts?: pulumi.CustomResourceOptions): FloatingIpAssignment {
        return new FloatingIpAssignment(name, <any>state, { ...opts, id: id });
    }

    public readonly floatingIpId: pulumi.Output<number>;
    public readonly serverId: pulumi.Output<number>;

    /**
     * Create a FloatingIpAssignment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FloatingIpAssignmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FloatingIpAssignmentArgs | FloatingIpAssignmentState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: FloatingIpAssignmentState = argsOrState as FloatingIpAssignmentState | undefined;
            inputs["floatingIpId"] = state ? state.floatingIpId : undefined;
            inputs["serverId"] = state ? state.serverId : undefined;
        } else {
            const args = argsOrState as FloatingIpAssignmentArgs | undefined;
            if (!args || args.floatingIpId === undefined) {
                throw new Error("Missing required property 'floatingIpId'");
            }
            if (!args || args.serverId === undefined) {
                throw new Error("Missing required property 'serverId'");
            }
            inputs["floatingIpId"] = args ? args.floatingIpId : undefined;
            inputs["serverId"] = args ? args.serverId : undefined;
        }
        super("hcloud:index/floatingIpAssignment:FloatingIpAssignment", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FloatingIpAssignment resources.
 */
export interface FloatingIpAssignmentState {
    readonly floatingIpId?: pulumi.Input<number>;
    readonly serverId?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a FloatingIpAssignment resource.
 */
export interface FloatingIpAssignmentArgs {
    readonly floatingIpId: pulumi.Input<number>;
    readonly serverId: pulumi.Input<number>;
}
