// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDatacenter(args?: GetDatacenterArgs, opts?: pulumi.InvokeOptions): Promise<GetDatacenterResult> {
    args = args || {};
    return pulumi.runtime.invoke("hcloud:index/getDatacenter:getDatacenter", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDatacenter.
 */
export interface GetDatacenterArgs {
    readonly id?: number;
    readonly name?: string;
}

/**
 * A collection of values returned by getDatacenter.
 */
export interface GetDatacenterResult {
    readonly availableServerTypeIds: number[];
    readonly description: string;
    readonly id: number;
    readonly location: {[key: string]: any};
    readonly name: string;
    readonly supportedServerTypeIds: number[];
}
