// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getLocations(args?: GetLocationsArgs, opts?: pulumi.InvokeOptions): Promise<GetLocationsResult> {
    args = args || {};
    return pulumi.runtime.invoke("hcloud:index/getLocations:getLocations", {
        "locationIds": args.locationIds,
    }, opts);
}

/**
 * A collection of arguments for invoking getLocations.
 */
export interface GetLocationsArgs {
    readonly locationIds?: string[];
}

/**
 * A collection of values returned by getLocations.
 */
export interface GetLocationsResult {
    readonly descriptions: string[];
    readonly locationIds?: string[];
    readonly names: string[];
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
