// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSshKey(args?: GetSshKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetSshKeyResult> {
    args = args || {};
    return pulumi.runtime.invoke("hcloud:index/getSshKey:getSshKey", {
        "fingerprint": args.fingerprint,
        "id": args.id,
        "name": args.name,
        "selector": args.selector,
        "withSelector": args.withSelector,
    }, opts);
}

/**
 * A collection of arguments for invoking getSshKey.
 */
export interface GetSshKeyArgs {
    readonly fingerprint?: string;
    readonly id?: number;
    readonly name?: string;
    readonly selector?: string;
    readonly withSelector?: string;
}

/**
 * A collection of values returned by getSshKey.
 */
export interface GetSshKeyResult {
    readonly fingerprint: string;
    readonly id?: number;
    readonly labels: {[key: string]: any};
    readonly name: string;
    readonly publicKey: string;
    readonly selector?: string;
    readonly withSelector?: string;
}
